// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHAJJi-TftsaMBxgM4QIQPFQdNudltuao',
    appId: '1:203787925583:web:96971bbb9386496199123a',
    messagingSenderId: '203787925583',
    projectId: 'dungeonmind-ea23c',
    authDomain: 'dungeonmind-ea23c.firebaseapp.com',
    databaseURL: 'https://dungeonmind-ea23c-default-rtdb.firebaseio.com',
    storageBucket: 'dungeonmind-ea23c.firebasestorage.app',
    measurementId: 'G-2CVW5G8MR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4EXNpXDFHNY1ofA1SISrBEkRwn5hVuo',
    appId: '1:203787925583:android:94ab6990d4f5295099123a',
    messagingSenderId: '203787925583',
    projectId: 'dungeonmind-ea23c',
    databaseURL: 'https://dungeonmind-ea23c-default-rtdb.firebaseio.com',
    storageBucket: 'dungeonmind-ea23c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vpY64MkbD4en2UXHgzmX5gjmAgaANTQ',
    appId: '1:203787925583:ios:6be4f02bcb38cf5b99123a',
    messagingSenderId: '203787925583',
    projectId: 'dungeonmind-ea23c',
    databaseURL: 'https://dungeonmind-ea23c-default-rtdb.firebaseio.com',
    storageBucket: 'dungeonmind-ea23c.firebasestorage.app',
    iosClientId: '203787925583-c8550m5cqlth6pfmmdsgv1ii4hb6mcbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vpY64MkbD4en2UXHgzmX5gjmAgaANTQ',
    appId: '1:203787925583:ios:6be4f02bcb38cf5b99123a',
    messagingSenderId: '203787925583',
    projectId: 'dungeonmind-ea23c',
    databaseURL: 'https://dungeonmind-ea23c-default-rtdb.firebaseio.com',
    storageBucket: 'dungeonmind-ea23c.firebasestorage.app',
    iosClientId: '203787925583-c8550m5cqlth6pfmmdsgv1ii4hb6mcbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHAJJi-TftsaMBxgM4QIQPFQdNudltuao',
    appId: '1:203787925583:web:0a87783f50e7ff3d99123a',
    messagingSenderId: '203787925583',
    projectId: 'dungeonmind-ea23c',
    authDomain: 'dungeonmind-ea23c.firebaseapp.com',
    databaseURL: 'https://dungeonmind-ea23c-default-rtdb.firebaseio.com',
    storageBucket: 'dungeonmind-ea23c.firebasestorage.app',
    measurementId: 'G-05KF88RMYW',
  );
}
